### PR TITLE
Reflect job-start/stop API changes in schema MODHAADM-5

### PR DESCRIPTION
**Pull request by nielserik**

### CODE REVIEW

**Comment by nielserik** [comment]
The start/stop job APIs changed a while back: Takes no content but an ID on the path, and both are PUTs. Aligned the Open API schema accordingly I hope.

**Review by MikeTaylor — APPROVED** [review]
Looks good to me.

Nice work on catching my mistake of using POST_RESPONSE instead of PUT_RESPONSE!

**Comment by nielserik** [comment]
Thanks @MikeTaylor. No mistake on your part, I think, It used to be a POST.

**Comment by MikeTaylor** [comment]
Oh, even better! :-)

**Pull request merged**
